version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - devdojo_data:/var/lib/mysql_springboot
volumes:
  devdojo_data: